name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run typecheck
      - run: npm run test:ci
      - run: npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          install-chromedriver: true
      - name: Install matching ChromeDriver
        run: |
          set -euxo pipefail
          CHROME_VERSION=$(google-chrome --version | grep -oE '[0-9.]*' | head -1)
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d. -f1)
          echo "Chrome version: $CHROME_VERSION, major: $CHROME_MAJOR"
          npm install -g chromedriver@$CHROME_MAJOR
          chromedriver --version

      - run: npm ci
      - run: npm run build
      - name: Run E2E (auto-start static server)
        run: npx jest -c ./e2e/jest.e2e.config.cjs --runInBand
        env:
          CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
